spring.application.name=api-gateway
server.port=8080
spring.cloud.gateway.routes[0].id=compound-interest-microservice
spring.cloud.gateway.routes[0].uri=lb://compound-interest-microservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/compound-interest/